# Generated by Django 2.2.1 on 2019-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
